### ISSUE TITLE
Uncaught Exception Restarting the Service

### ISSUE THREAD

**Issue by guilherme-rauen** [jambonz/jambonz-api-server#226]
Hello @davehorton / @xquanluu,

I had a restart in the `api-server` last night, and when I inspected the logs in the old container I saw this error:

```
2023-08-30T00:52:00+02:00 {"level":30,"time":1693349520769,"pid":1,"hostname":"api-server-5b8d86759d-6j8gh","msg":"upgraded to websocket, url: /v1/record/aws_s3","v":1}
2023-08-30T00:52:00+02:00 {"level":30,"time":1693349520770,"pid":1,"hostname":"api-server-5b8d86759d-6j8gh","obj":{"sampleRate":8000,"mixType":"stereo","callSid":"f23fd4a2-60cd-4268-ac68-0a8ace3a0962","direction":"inbound",...}
2023-08-30T00:52:26+02:00 RangeError: start offset of Int16Array should be a multiple of 2
2023-08-30T00:52:26+02:00     at new Int16Array (<anonymous>)
2023-08-30T00:52:26+02:00     at PCMToMP3Encoder._transform (/opt/app/lib/record/encoder.js:18:21)
2023-08-30T00:52:26+02:00     at Transform._write (node:internal/streams/transform:175:8)
2023-08-30T00:52:26+02:00     at writeOrBuffer (node:internal/streams/writable:392:12)
2023-08-30T00:52:26+02:00     at _write (node:internal/streams/writable:333:10)
2023-08-30T00:52:26+02:00     at Writable.write (node:internal/streams/writable:337:10)
2023-08-30T00:52:26+02:00     at Duplex.ondata (node:internal/streams/readable:766:22)
2023-08-30T00:52:26+02:00     at Duplex.emit (node:events:513:28)
2023-08-30T00:52:26+02:00     at Duplex.emit (node:domain:489:12)
2023-08-30T00:52:26+02:00     at addChunk (node:internal/streams/readable:324:12)
2023-08-30T00:52:26+02:00 {"level":50,"time":1693349546310,"pid":1,"hostname":"api-server-5b8d86759d-6j8gh","msg":"Uncaught exception error caught. Error was: start offset of Int16Array should be a multiple of 2","v":1}
```
I need to check what call we were having at that moment to see if feature-server can say anything else. But at the moment the most important thing is to try to catch this error and avoid the crash of the service.

Refer: https://github.com/jambonz/jambonz-api-server/blob/main/lib/record/encoder.js#L16-L41

Thanks!

**Comment by guilherme-rauen** [comment]
Oh, just saw that we already have an issue opened for this: https://github.com/jambonz/jambonz-api-server/issues/200

**Comment by davehorton** [comment]
minimally we need to catch this exception.  We should also try to figure out how to recreate to fix root cause

**Comment by xquanluu** [comment]
I agreed to put a try catch there firstly. the strange thing is that some how the feature server was not sending even pagkage count to api-server for stereo audio stream

Hi @guilherme-rauen Is it easy for you to reproduce the issue? Could you tell me the steps to reproduce it?

**Comment by guilherme-rauen** [comment]
Hi @xquanluu,

No, I don't actually know how to reproduce it. But I see it from time to time.
It happened today again...

2023-09-19T09:46:06+02:00 RangeError: start offset of Int16Array should be a multiple of 2
2023-09-19T09:46:06+02:00     at new Int16Array (<anonymous>)
2023-09-19T09:46:06+02:00     at PCMToMP3Encoder._transform (/opt/app/lib/record/encoder.js:18:21)
2023-09-19T09:46:06+02:00     at Transform._write (node:internal/streams/transform:175:8)
2023-09-19T09:46:06+02:00     at writeOrBuffer (node:internal/streams/writable:392:12)
2023-09-19T09:46:06+02:00     at _write (node:internal/streams/writable:333:10)
2023-09-19T09:46:06+02:00     at Writable.write (node:internal/streams/writable:337:10)
2023-09-19T09:46:06+02:00     at Duplex.ondata (node:internal/streams/readable:766:22)
2023-09-19T09:46:06+02:00     at Duplex.emit (node:events:514:28)
2023-09-19T09:46:06+02:00     at Duplex.emit (node:domain:489:12)
2023-09-19T09:46:06+02:00     at addChunk (node:internal/streams/readable:324:12)
2023-09-19T09:46:06+02:00 {"level":50,"time":1695109566044,"pid":1,"hostname":"api-server-564bf678f4-f5g7p","msg":"Uncaught exception error caught. Error was: start offset of Int16Array should be a multiple of 2","v":1}

**Comment by davehorton** [comment]
@xquanluu can you add the try-catch block needed?
